# Uncomment the next line to define a global platform for your project
  platform :ios, ‘8.0’
  use_frameworks!

target 'PhotoBrowser-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	pod 'Kingfisher'

  # Pods for PhotoBrowser-swift

  target 'PhotoBrowser-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoBrowser-swiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
